image: ubuntu/22.04
packages:
  - postgresql
tasks:
  - build: |
      cd lakehouse
      wget https://go.dev/dl/go1.20.2.linux-amd64.tar.gz
      make build
  - test: |
      cd lakehouse
      make test
  - lint: |
      cd lakehouse
      make lint
