image: ubuntu/22.04
arch: amd64
packages:
  - postgresql
secrets:
  - 46f739e5-4538-45dd-a79f-bf173b7a2ed9
tasks:
  - build: |
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&
      sudo apt-get install -y nodejs
      wget https://go.dev/dl/go1.20.2.linux-amd64.tar.gz
      sudo tar -C /usr/local -xzf go1.20.2.linux-amd64.tar.gz
      export PATH=/usr/local/go/bin:$PATH
      cd lakehouse
      make build
  - test: |
      export PATH=/usr/local/go/bin:$PATH
      cd lakehouse
      make test
  - lint: |
      export PATH=/usr/local/go/bin:$PATH
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.52.2
      cd lakehouse
      make lint
  - deploy: |
      export PATH=/usr/local/go/bin:$PATH
      cd lakehouse
      make deploy
